export enum AppTypeEnum {
  USER = 'USER',
  COLLABORATOR = 'COLLABORATOR',
  PARTNER = 'PARTNER',
}

export enum SearchTypeEnum {
  CATEGORIES = 'CATEGORIES',
  PARTNERS = 'PARTNERS',
  PRODUCTS = 'PRODUCTS',
  ALL = 'ALL',
}

export enum DeliveryStatusEnum {
  WAITING_ACCEPT = 'WAITING_ACCEPT',
  NEW_ORDER = 'NEW_ORDER',
  WAITING_PAYMENT = 'WAITING_PAYMENT',
  PREPARING = 'PREPARING',
  WAITING_COLLABORATOR = 'WAITING_COLLABORATOR',
  ON_THE_PARTNER = 'ON_THE_PARTNER',
  ORDER_READY = 'ORDER_READY',
  WAY_TO_CLIENT = 'WAY_TO_CLIENT',
  WAITING_CLIENT = 'WAITING_CLIENT',
  DELIVERED = 'DELIVERED',
  PROCESSING = 'PROCESSING',
  WAITING_ORDER_CONFIRMATION = 'WAITING_ORDER_CONFIRMATION',
  DELIVERY_REFUSED = "DELIVERY_REFUSED",
  DELIVERY_ACCEPTED = "DELIVERY_ACCEPTED",
  ORDER_REFUSED = 'ORDER_REFUSED',
  ORDER_FINISHED = 'ORDER_FINISHED',
  ORDER_CANCELED = 'ORDER_CANCELED',
}

export enum PaymentCCStatus {
  DECLINED = 'DECLINED',
  FAILED = 'FAILED',
  NOT_AUTHORIZED = 'NOT_AUTHORIZED',
  CONFIRMED = 'CONFIRMED',
  CUSTOMER_PAID_BACK = 'CUSTOMER_PAID_BACK',
  BANK_PAID_BACK = 'BANK_PAID_BACK',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
}

export enum PaymentWebhookEnum {
  DOCUMENT_STATUS_CHANGED = "DOCUMENT_STATUS_CHANGED",
  DIGITAL_ACCOUNT_STATUS_CHANGED = "DIGITAL_ACCOUNT_STATUS_CHANGED",
  TRANSFER_STATUS_CHANGED = "TRANSFER_STATUS_CHANGED",
  P2P_TRANSFER_STATUS_CHANGED = "P2P_TRANSFER_STATUS_CHANGED",
  PAYMENT_NOTIFICATION = "PAYMENT_NOTIFICATION",
  CHARGE_STATUS_CHANGED = "CHARGE_STATUS_CHANGED",
}
