export enum EventTypeStatus {
  ENABLED = 'ENABLED',
  DEPRECATED = 'DEPRECATED',
}

export enum EventTypesName {
  DOCUMENT_STATUS_CHANGED = 'DOCUMENT_STATUS_CHANGED',
  DIGITAL_ACCOUNT_CREATED = 'DIGITAL_ACCOUNT_CREATED',
  DIGITAL_ACCOUNT_STATUS_CHANGED = 'DIGITAL_ACCOUNT_STATUS_CHANGED',
  TRANSFER_STATUS_CHANGED = 'TRANSFER_STATUS_CHANGED',
  P2P_TRANSFER_STATUS_CHANGED = 'P2P_TRANSFER_STATUS_CHANGED',
  PAYMENT_NOTIFICATION = 'PAYMENT_NOTIFICATION',
  CHARGE_STATUS_CHANGED = 'CHARGE_STATUS_CHANGED',
}
