export enum PaymentCardStatus {
  DECLINED = 'DECLINED',
  FAILED = 'FAILED',
  NOT_AUTHORIZED = 'NOT_AUTHORIZED',
  CONFIRMED = 'CONFIRMED',
  CUSTOMER_PAID_BACK = 'CUSTOMER_PAID_BACK',
  BANK_PAID_BACK = 'BANK_PAID_BACK',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
}
